workflows:
  android-workflow:
    name: Build WhisperVox APK
    max_build_duration: 15
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Build APK
        script: |
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
