workflows:
  android-workflow:
    name: Build WhisperVox APK
    max_build_duration: 15
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Give execution permission
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew :app:clean
          ./gradlew :app:assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
